import Head from 'next/head'
import Image from 'next/image'
import axios from "axios";
import AddButton from '../components/AddButton';
import Add from '../components/Add'
import Featured from '../components/Featured'
import PizzaList from '../components/PizzaList'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import Product from "../models/Product";
import dbConnect from "../util/mongo";


export default function Home({pizzaList, admin}) {
  const [close,setClose]=useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Anas khan pizza store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Featured/>
        {admin && <AddButton setClose={setClose}/>}
        {<PizzaList pizzaList={pizzaList}/>}
        {!close && <Add setClose={setClose}/>}
    </div>
  )
}

export const getServerSideProps=async(ctx)=>{
  const myCookie = ctx.req?.cookies || "";
  let admin = false;
  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }
  await dbConnect();
  let products = [];
  try {
    products = await Product.find();
    products = await JSON.parse(JSON.stringify(products));
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      pizzaList: products,
      admin,
    },
  };
 }